### ISSUE TITLE
Why do the feature-cards show a pointer cursor despite not being clickable?

### ISSUE THREAD

**Issue by Lenni009** [MeridianGH/kalliope-server#1]
The feature cards ("Full support", "High quality", "YouTube search"...) have a `cursor: pointer`, but aren't actually clickable. That's confusing for users. Since this property is explicitly written in the CSS of that file, I figured to ask first before submitting a PR to fix this.

**Comment by MeridianGH** [comment]
That is indeed a valid concern, and I can't seem to recall why I placed that there.
I would assume because I thought it makes the hover effect more noticeable but after comparing it with the default cursor I would definitely agree with you.

Feel free to submit a pull request.
